### ISSUE TITLE
Developing a process for issue review and contributions

### ISSUE THREAD

**Issue by lindsmith** [ga4gh/quality-control-wgs#1]
To ensure good work practices, we need to decide upon a process for contributing to the repo.
Following up to our Dec. 13th call, I have reviewed the issues/PR processes followed in other GA4GH projects and prepared a PR for review. Some thoughts to consider:

- Do we want to include some kind of formal voting/review as part of PR approval? Right now, community review is implied in 
> Open issues and PRs are reviewed and triaged in our QC of WGS calls.
- Would it be useful to include definitions of product maintainer, contributor, subgroup lead, etc.?
- Do we want to create PR/Issue templates for contributors?
- Do we want instructions on how we'd prefer use of Github labels, milestones, and the project board?
- Not yet described are Github features like code review limits. Do we want to enable any of these features?

Examples: [VRS Development Process](https://vrs.ga4gh.org/en/stable/appendices/development_process.html), [VRS CONTRIBUTING.md](https://github.com/ga4gh/vrs/blob/8e04083d4ea26bd2883421bba67e2de900f73cb0/CONTRIBUTING.md), [TRS CONTRIBUTING.md](https://github.com/ga4gh/tool-registry-service-schemas/blob/develop/CONTRIBUTING.md), [Phenopackets CONTRIBUTING.md](https://github.com/phenopackets/phenopacket-schema/blob/master/CONTRIBUTING.rst)

**Comment by ohofmann** [comment]
@lindsmith Thanks for starting the discussion! Do we general templates for GA4GH repos for some of these? I suspect PR/issue templates could be relatively generic, as could be an agreed-upon set of labels as starting points and what the expectations for maintainer and contributors are. Happy to go with _ad hoc_ definitions for now and use them to start a broader discussion.

**Comment by lindsmith** [comment]
@ohofmann Unfortunately no general use templates _yet_, but this has been submitted as a best practice need ([see the Airtable board](https://airtable.com/shrVFQLOe4vCuGJ03/tblqXtIv1f6ORfoFR)) for further development & discussion.

I think we will need to go with our own _ad hoc_ definitions for now. I agree - let's share our decisions to generate some broader discussion. I'm assuming the Best Practices team will be reaching out to groups in the future to collect this information anyway.

**Comment by ohofmann** [comment]
Okay! @skanwal - can you work with Alexis and the team to port over some of our ICA (and UMCCR) templates for reports/issues or PRs?

**Comment by skanwal** [comment]
Hi @lindsmith - Re adding templates for issues and PRs, I am not able to access "Settings" for this repository. I think because I am not part of GA4GH github org.

Is it possible for you to add me?

**Comment by lindsmith** [comment]
Hi @skanwal - I updated the permission, can you access the settings now? Please let me know if not and I have one other fix to try.

**Comment by skanwal** [comment]
That worked, Lindsay, Thanks.

**Comment by skanwal** [comment]
Spoke too soon. I am only able to view limited options in "Settings".
Ability to setup templates is still not accessible.

**Comment by lindsmith** [comment]
@skanwal - ok, you are now an admin to the repo! Working now?

**Comment by skanwal** [comment]
Yes, I can see complete options now. Thanks. I plan to set-up templates next week.
