### ISSUE TITLE
improved `read_mapping_quality` metric definition, renamed as `pct_reads_mapped`

### ISSUE THREAD

**Issue by nicolas-bertin** [ga4gh/quality-control-wgs#12]
proposal to improved `read_mapping_quality` metric definition from 

https://github.com/ga4gh/quality-control-wgs/blob/e692682078a3f47b8160cc1ef74614227264b847/metrics_definitions/metrics_definitions.md?plain=1#L69-L75 

to [Edit]

https://github.com/ga4gh/quality-control-wgs/blob/bddde198a26f1311a0188f8792b71d6fe704949d/metrics_definitions/metrics_definitions.md?plain=1#L43-L49

see #7

**Comment by mhebrard** [comment]
* Fix Typo
* Clarify MQ criteria - include all mapped reads - no MQ filter applied
* Include duplicated reads - the goal of this metric should be to get a sense of how much of the library map to human vs other species

https://github.com/ga4gh/quality-control-wgs/blob/bddde198a26f1311a0188f8792b71d6fe704949d/metrics_definitions/metrics_definitions.md?plain=1#L43-L49
