### ISSUE TITLE
Evenness of Coverage QC Metric

### ISSUE THREAD

**Issue by gobelina** [ga4gh/quality-control-wgs#15]
Hi there!

As Ivo Gut mentioned, at CNAG we use the simple ratio of median/mean coverage to estimate the evenness. It has the advantage that it is easy to calculate and to interpret. The expectation is that a sample with an even coverage will have a  median/mean ratio of around 1. In our experience, this ratio works well for germline samples and can be estimated using, for example, GATK's depth of coverage (although not all versions include this feature).

The other metric we have used is the FWHM method, where we look at the full width at half maximum of the main cloud (a measure of dispersion), which corresponds to the main copy number state of the sample. This estimate is also calculated with GATK's depth of coverage. It is not as straight forward and may be misleading with cancer samples.

It would be nice to know if other ways to calculate the evenness of coverage have been explored by other groups. Thank you!!
Gabriela Aguileta (CNAG)

**Comment by justinjj24** [comment]
> The expectation is that a sample with an even coverage will have a median/mean ratio of around 1. In our experience, this ratio works well for germline samples

Agree on your comment!

> It would be nice to know if other ways to calculate the evenness of coverage have been explored by other groups.

Illumina DRAGEN QC metrics report..
 1) mean median autosomal coverage ratio over autosomal region and 
 2) Uniformity of coverage by calculating Percentage of sites with coverage greater than 20% of the mean coverage in region

**Comment by nicolas-bertin** [comment]
Hi @gobelina, 

Are you proposing that  "the use the simple ratio of median/mean coverage to estimate the evenness" be 
- a novel additional metric, complementing the currently existing **genome coverage uniformity**
- or, an updated definition of the existing **genome coverage uniformity**

fyi, existing/current **genome coverage uniformity** :
https://github.com/ga4gh/quality-control-wgs/blob/e692682078a3f47b8160cc1ef74614227264b847/metrics_definitions/metrics_definitions.md?plain=1#L62-L67

**Comment by gobelina** [comment]
Hi @nicolas-bertin,

No, the idea was only to expand on Ivo's comment during our last meeting about the measures of coverage evenness that we use in our lab. The genome coverage uniformity measure you already have is fine for us too.

**Comment by nicolas-bertin** [comment]
Thanks @gobelina 
...closing the issue
