### ISSUE TITLE
add novel `insert size standard deviation` metric

### ISSUE THREAD

**Issue by justinjj24** [ga4gh/quality-control-wgs#16]
In revisiting the metric related to insert size stats, it was decided that instaed of returning a [mean, std-dev] tuple, it woud be better to have two metrics returning a single value  (see https://github.com/ga4gh/quality-control-wgs/blob/precise-metrics-definition/metrics_definitions/metrics_definitions.md#mean-insert-size )
Therefore a `insert-size-stddev` metrics probably needs to be defined

**Comment by justinjj24** [comment]
### insert size standard deviation
  
 - **ID:** insert_size_std_deviation
 - **Description:** The insert size standard deviation of short paired-end sequencing [high quality](#high-quality-reads), [non duplicated](#duplicated-reads) reads, [primary alignments](#primary-alignments), mapped on [GRCh38 assembly](#grch38-assembly). No minimum [mapping quality](#mapping-quality) is imposed. It is critical that the (BAM/CRAM) alignment files be readily marked for [duplicated reads](#duplicated-reads) 
 - **Implementation details:** In the NPM-sample-QC reference implementation it is computed using [samtools stats](##samtools-stats), reporting the `MAPPING/ALIGNING SUMMARY,,Insert length: mean` field. Only the [primary alignments](#primary-alignments), mapped on GRCh38 assembly are considered. No filter on duplicated reads, and mapping qualiy is applied.
 - **Functionally equivalent implementations:** Are considered functionally equivalent alternative implementations producing values within 1% of those reported by the reference implementation when computing the metric for data in the benchmark_resources 
   - [Candidate] [DRAGEN v3.7.6](#dragen). Extracted from [sample-id].mapping_metrics.csv, key name: `MAPPING/ALIGNING SUMMARY,,Insert length: standard deviation`

**Comment by mhebrard** [comment]
Linked to #14 , should we keep duplicates
