### ISSUE TITLE
add novel `cross_contamination_rate` metric

### ISSUE THREAD

**Issue by justinjj24** [ga4gh/quality-control-wgs#17]
It has been proposed and approved in-principle during GA4GH QC of WGS Standards - Follow up Tuesday Mar. 28 Meeting.

- **ID:**  cross_contamination_rate
- **Description:** Detecting and estimating inter-sample DNA contamination level of short paired-end sequencing [high quality](#high-quality-reads) reads, mapped on [GRCh38 assembly](#grch38-assembly), no minimum [mapping quality](#mapping-quality) and alignment filters are imposed.
- **Implementation details:** The estimation of inter-sample DNA contamination of short paired-end sequencing [high quality](#high-quality-reads), aligned sequence reads (BAM/CRAM) mapped on [GRCh38 assembly](#grch38-assembly) with pre-calculated reference panel of [1000 Genome Project(1000g) dataset](#1000-Genome-Project(1000g)-dataset) from the VerifyBamID resource using [VerifyBamID2](#VerifyBamID2) with NumPC “4” (# of Principal Components used in estimation), the key information “FREEMIX” in “.selfSM” in the results indicates the estimated contamination level. 
- **Functionally equivalent implementations:** Are considered functionally equivalent alternative implementations producing values within 1% of those reported by the reference implementation when computing the metric for data in the benchmark resources
   - [Candidate] [All Of Us QC Report: Q2 2022 release](#All-Of-Us-QC-Report). QC key name : key information FREEMIX in “.selfSM”
  
### 1000 Genome Project(1000g) dataset
  Pre-calculated reference panel of 1000 Genome Project(1000g) dataset:
  UDPath: https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.UD 
  BedPath: https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.bed 
  MeanPath: https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.mu 

### VerifyBamID2
[https://github.com/Griffan/VerifyBamID](https://github.com/Griffan/VerifyBamID)

### All Of Us QC Report
[https://www.researchallofus.org/wp-content/themes/research-hub-wordpress-theme/media/2022/06/All%20Of%20Us%20Q2%202022%20Release%20Genomic%20Quality%20Report.pdf](https://www.researchallofus.org/wp-content/themes/research-hub-wordpress-theme/media/2022/06/All%20Of%20Us%20Q2%202022%20Release%20Genomic%20Quality%20Report.pdf)

**Comment by mhebrard** [comment]
Add cross contamination in #7 

https://github.com/ga4gh/quality-control-wgs/blob/f21759a92df940b8bb4b9b174e642533c69013a2/metrics_definitions/metrics_definitions.md?plain=1#L82-L88

**Comment by mhebrard** [comment]
Can we confirm the status of 
* Duplicated reads
* Clipped bases 
* Mapping quality ?

**Comment by mhebrard** [comment]
From https://github.com/Griffan/VerifyBamID/tree/7e7172c2b45f61c72d35d94708a7a5c2f271ee3a
>
--incl-flags     [Int] Required flags: skip reads with mask bits unset [null]
--excl-flags     [Int] Filter flags: skip reads with mask bits set [UNMAP,SECONDARY,QCFAIL,DUP]

From https://github.com/Griffan/VerifyBamID/blob/master/main.cpp#L50-L65 

```
  mplp_conf_t mplp;
  memset(&mplp, 0, sizeof(mplp_conf_t));
  mplp.min_mq = 2;
  mplp.min_baseQ = 13;
  mplp.capQ_thres = 40;
  mplp.max_depth = MPLP_MAX_DEPTH;
  mplp.max_indel_depth = MPLP_MAX_INDEL_DEPTH;
  mplp.openQ = 40;
  mplp.extQ = 20;
  mplp.tandemQ = 100;
  mplp.min_frac = 0.002;
  mplp.min_support = 1;
  bool noOrphan = false;
  mplp.flag = /*MPLP_NO_ORPHAN |*/ MPLP_REALN | MPLP_SMART_OVERLAPS;
  mplp.rflag_filter = BAM_FUNMAP | BAM_FSECONDARY | BAM_FQCFAIL | BAM_FDUP;
  mplp.output_fname = NULL;
```

Therefore confirming that VerifyBamID2 by default exclude duplicates, secondary alignments, min MQ = 2, min BQ = 13

We should follow best practice in the definition, request to exclude duplicates (and secondary alignment).
We leave the mapping quality out of the formal definition - & specify the default param of the ref implementation

**Comment by mhebrard** [comment]
Update the definition to specify remove duplicates
