### ISSUE TITLE
Post Variant Calling Metric "SVN count" ID should probly by `pass_snv_count` 

### ISSUE THREAD

**Issue by c-BIG-admin** [ga4gh/quality-control-wgs#23]
To be more aligned with Post Alignment Metric IDs, it might be better to name (ie metric's ID) it `pass_snv_count`

https://github.com/ga4gh/quality-control-wgs/blob/d32d9272da2341cb6031af64167e74e2f88f7f37/metrics_definitions/metrics_definitions.md?plain=1#L99

@justinjj24, What do you think ?

**Comment by justinjj24** [comment]
Agree.
Updated the metric definiton **ID** as follows..
- Count: SNVs - ID: **count_snvs_pass**
- Count: Insertions - ID: **count_insertions_pass**
- Count: Deletions - ID: **count_deletions_pass**
- Ratio: Insertions/Deletions -  ID: **ratio_insertion_deletion_pass**
- Ratio: Heterozygous/Homozygous (SNVs) - ID: **ratio_heterozygous_homzygous_snv_pass**
- Ratio: Heterozygous/Homozygous (indels) - ID: **ratio_heterozygous_homzygous_indel_pass**
- Ratio: Transitions/Transversions (ti/tv) - ID: **ratio_transitions_transversions_pass**
