### ISSUE TITLE
Post Variant Calling Metrics pertaining to insertion and deletion metrics

### ISSUE THREAD

**Issue by justinjj24** [ga4gh/quality-control-wgs#29]
Lets **have two sets of indel metrics** 
 - one for short <50bp (typically obtained using short-varioant caller) ;and 
 - one for "any" (ie short <50bp indels typically obtained using short-varioant caller as well as long > 50bp  indels typically obtained using specialized SV callers) for each of the Post Variant Calling Metrics pertaining to insertion and deletion metrics. The latter would be identified using VCF INFO/SVTYPE, the former might be implicite (TBC)

**Comment by justinjj24** [comment]
- Insertions are only considered in this metric short, less than 50bp, insertions as commonly identified by most short reads variant callers. Structural variations which include insertions larger than 50bp and which are typically identified using dedicated SV callers are not considered.

- Deletions are only considered in this metric short, less than 50bp, deletion as commonly identified by most short reads variant callers. Structural variations which include deletions larger than 50bp and which are typically identified using dedicated SV callers are not considered.

Insertions:
https://github.com/ga4gh/quality-control-wgs/blob/390020fb1bb5aff77b96acfa84690b2c04c102cb/metrics_definitions/metrics_definitions.md?plain=1#L110

Deletions:
https://github.com/ga4gh/quality-control-wgs/blob/390020fb1bb5aff77b96acfa84690b2c04c102cb/metrics_definitions/metrics_definitions.md?plain=1#L118

**Comment by justinjj24** [comment]
Latest VCF version 4.4 `Section 3`(https://samtools.github.io/hts-specs/VCFv4.4.pdf) 

`##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">`

This field has been **deprecated** due to redundancy with ALT. Refer to section 1.4.5 for the set of valid ALT field
symbolic structural variant alleles.

`##INFO=<ID=SVLEN,Number=A,Type=Integer,Description="Length of structural variant">`

One value for each ALT allele.
SVLEN must be specified for symbolic structural variant alleles. SVLEN is defined for INS, DUP, INV , and
DEL symbolic alleles as the number of the inserted, duplicated, inverted, and deleted bases respectively.

**Comment by mhebrard** [comment]
current metric definition specify that we consider only indels, less than 50bp
