### ISSUE TITLE
improved `yield_bp_q30` metric definition 

### ISSUE THREAD

**Issue by nicolas-bertin** [ga4gh/quality-control-wgs#8]
proposal to improve `yield_bp_q30` metric definition from

https://github.com/ga4gh/quality-control-wgs/blob/e692682078a3f47b8160cc1ef74614227264b847/metrics_definitions/metrics_definitions.md?plain=1#L19-L35

to [edit: fix typo]

https://github.com/ga4gh/quality-control-wgs/blob/bddde198a26f1311a0188f8792b71d6fe704949d/metrics_definitions/metrics_definitions.md?plain=1#L21-L27

see #7

**Comment by nicolas-bertin** [comment]
see proposal in #7

**Comment by justinjj24** [comment]
typo in https://github.com/ga4gh/quality-control-wgs/blob/0290612d0237078dea7ae38dc13e680189fc46d1/metrics_definitions/metrics_definitions.md?plain=1#L25 [GATK Picard’s CollectQualityYieldMetric](#picard-collectqualityyieldmetrics) should read  [GATK Picard’s CollectQualityYieldMetrics](#picard-collectqualityyieldmetrics)

**Comment by mhebrard** [comment]
Fix typo & phrasing:

https://github.com/ga4gh/quality-control-wgs/blob/bddde198a26f1311a0188f8792b71d6fe704949d/metrics_definitions/metrics_definitions.md?plain=1#L21-L27
