### ISSUE TITLE
improved `mean_autosome_coverage` metric definition

### ISSUE THREAD

**Issue by nicolas-bertin** [ga4gh/quality-control-wgs#9]
proposal to improve `mean_autosome_coverage` metric definition from

https://github.com/ga4gh/quality-control-wgs/blob/e692682078a3f47b8160cc1ef74614227264b847/metrics_definitions/metrics_definitions.md?plain=1#L36-L54

to [edit: Fix typo]

https://github.com/ga4gh/quality-control-wgs/blob/bddde198a26f1311a0188f8792b71d6fe704949d/metrics_definitions/metrics_definitions.md?plain=1#L29-L34

see #7

**Comment by justinjj24** [comment]
typo :  expluded ->   excluded

**Comment by mhebrard** [comment]
Fix typo

https://github.com/ga4gh/quality-control-wgs/blob/bddde198a26f1311a0188f8792b71d6fe704949d/metrics_definitions/metrics_definitions.md?plain=1#L29-L34
